# calculate stock return/volatility during which period
period: '5y'
# valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max

interval: '1d'
# valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo

# stocks to be included in the portfolio, {ticker: company}
stocks: {
  'FB': 'Facebook',
  'AMZN': 'Amazon',
  'AAPL': 'Apple',
  'NFLX': 'Netflix',
  'GOOGL': 'Google'
}

# whether allow purchasing fractional shares in the model 
fractional_shares: True

# total investment amount, required when fractional_shares = False
investment_amount: